### PR TITLE
Release 0.1 - To Master

### PR DESCRIPTION
**Pull request by kevinlaw91**
Merge everything from #2 to master

### CODE REVIEW

**Comment by kevinlaw91** [comment]
@ohjacking, done 😉

**Comment by ohjacking** [comment]
@kevinlaw91 seems like u add the picture to the code, how to view it yea

**Comment by cd11103** [comment]
Tunggu.. Sedang setup

**Comment by cd11103** [comment]
http://beta.vivicrew.com/

**Pull request merged**
